### 회원 추가 테스트 (1)
POST http://localhost:8080/members/post
Content-Type: application/json

{
  "name": "Derek",
  "email": "test@gmail.com",
  "nickname": "Derek",
  "password": "password1!"
}

### 회원 추가 테스트 (2)
POST http://localhost:8080/members/post
Content-Type: application/json

{
  "name": "Steve",
  "email": "test2@gmail.com",
  "nickname": "Steve",
  "password": "password1!!"
}

### 이메일 존재여부 테스트
POST http://localhost:8080/members/post
Content-Type: application/json

{
"name": "Derek",
"email": "test@gmail.com",
"nickname": "Kevin",
"password": "password1!"
}

### 닉네임 존재 여부 테스트
POST http://localhost:8080/members/post
Content-Type: application/json

{
"name": "Derek",
"email": "test2@gmail.com",
"nickname": "Derek",
"password": "password1!"
}